services:
  # Backend API Service
  - type: web
    name: water-treatment-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CORS_ORIGINS
        value: "*"
        
  # Frontend Static Site
  - type: static
    name: water-treatment-frontend
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: water-treatment-api
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html