services:
  # Backend API Service
  - type: web
    name: water-treatment-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CORS_ORIGINS
        value: "*"
        
  # Frontend Static Site
  - type: static
    name: water-treatment-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: water-treatment-api
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html